name: Install Windows SDK and Run Signing Script

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Visual Studio Build Tools Installer
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"

    - name: Install Visual Studio Build Tools
      run: |
        Start-Process -FilePath "vs_buildtools.exe" -ArgumentList "--quiet", "--wait", "--add Microsoft.VisualStudio.Component.Windows10SDK.19041 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --installPath C:\BuildTools" -NoNewWindow -Wait

    - name: Verify Installation Directory
      run: |
        if (-Not (Test-Path "C:\BuildTools")) {
          Write-Error "Installation directory not found."
          exit 1
        }

    - name: List Installed Files in BuildTools
      run: |
        Get-ChildItem -Recurse "C:\BuildTools" | Format-Table -Property FullName, LastWriteTime

    - name: List Installed Files in Program Files (x86) Windows Kits
      run: |
        Get-ChildItem -Recurse "C:\Program Files (x86)\Windows Kits" | Format-Table -Property FullName, LastWriteTime

    - name: List Installed Files in Program Files (x86) Visual Studio
      run: |
        Get-ChildItem -Recurse "C:\Program Files (x86)\Microsoft Visual Studio" | Format-Table -Property FullName, LastWriteTime

    - name: Search for signtool.exe in all locations
      id: find-signtool
      run: |
        $paths = @(
          "C:\BuildTools",
          "C:\Program Files (x86)\Windows Kits\10\bin\x64",
          "C:\Program Files (x86)\Windows Kits\10\bin\x86",
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC",
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC"
        )
        $signtoolPath = $null
        foreach ($path in $paths) {
          $signtoolPath = Get-ChildItem -Path $path -Filter "signtool.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
          if ($signtoolPath) { break }
        }
        if (-not $signtoolPath) {
          Write-Error "signtool.exe not found."
          exit 1
        }
        echo "::set-output name=signtool::$signtoolPath"

    - name: Verify signtool
      run: |
        if (Test-Path "${{ steps.find-signtool.outputs.signtool }}") {
          "${{ steps.find-signtool.outputs.signtool }}" /?
        } else {
          Write-Error "signtool.exe not found in the expected directory."
        }

    - name: Run Sign Scripts
      run: |
        cd $env:GITHUB_WORKSPACE\BuildScripts\CodeSigning
        .\Sign.bat "$env:GITHUB_WORKSPACE\DotNet\hit.exe" "${{ steps.find-signtool.outputs.signtool }}"
